"""Post or update a Focus HUD comment on a GitHub pull request.

Uses the Actions ``GITHUB_TOKEN`` only — minimum scope is pull-requests:write.
Comments are marked with ``FOCUS_COMMENT_MARKER`` so re-runs update in place
instead of spamming new comments.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from focus.ci._http import request_json

FOCUS_COMMENT_MARKER = "<!-- focus-hud -->"


def render_pr_comment(hud_markdown: str) -> str:
    """Wrap HUD markdown for a PR comment (docs/HUD.md contract).

    Always includes ``FOCUS_COMMENT_MARKER`` so CI can find and update
    the same comment on later runs instead of posting duplicates.
    """
    body = hud_markdown.strip()
    footer = (
        "\n\n---\n"
        "<sub>Generated by Focus · evidence-based blast radius · "
        "[docs](https://github.com/j0viane/focus)</sub>\n"
    )
    if FOCUS_COMMENT_MARKER not in body:
        body = f"{FOCUS_COMMENT_MARKER}\n{body}"
    if "Generated by Focus" not in body:
        body = body + footer
    return body


def post_or_update_pr_comment(
    *,
    hud_markdown: str,
    token: str,
    repository: str,
    pr_number: int,
    api_url: str = "https://api.github.com",
) -> str:
    """Create or update the Focus HUD comment. Returns 'created' or 'updated'."""
    body = render_pr_comment(hud_markdown)
    owner, repo = repository.split("/", 1)
    comments = _list_issue_comments(api_url, token, owner, repo, pr_number)
    existing = next((c for c in comments if FOCUS_COMMENT_MARKER in c.get("body", "")), None)
    if existing:
        _patch_comment(api_url, token, owner, repo, int(existing["id"]), body)
        return "updated"
    _create_comment(api_url, token, owner, repo, pr_number, body)
    return "created"


def post_from_env(hud_path: Path) -> str:
    """Read HUD file and post using GitHub Actions environment variables."""
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    repository = os.environ.get("GITHUB_REPOSITORY")
    pr_number = os.environ.get("FOCUS_PR_NUMBER") or _pr_number_from_event()
    api_url = os.environ.get("GITHUB_API_URL", "https://api.github.com")
    if not token or not repository or not pr_number:
        raise RuntimeError(
            "Need GITHUB_TOKEN, GITHUB_REPOSITORY, and FOCUS_PR_NUMBER "
            "(or pull_request event payload) to post a comment."
        )
    return post_or_update_pr_comment(
        hud_markdown=hud_path.read_text(encoding="utf-8"),
        token=token,
        repository=repository,
        pr_number=int(pr_number),
        api_url=api_url,
    )


def _pr_number_from_event() -> str | None:
    path = os.environ.get("GITHUB_EVENT_PATH")
    if not path or not Path(path).is_file():
        return None
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    pr = payload.get("pull_request") or {}
    number = pr.get("number") or payload.get("number")
    return str(number) if number else None


def _list_issue_comments(
    api_url: str, token: str, owner: str, repo: str, pr_number: int
) -> list[dict]:
    url = f"{api_url}/repos/{owner}/{repo}/issues/{pr_number}/comments?per_page=100"
    return request_json("GET", url, token)


def _create_comment(
    api_url: str, token: str, owner: str, repo: str, pr_number: int, body: str
) -> None:
    url = f"{api_url}/repos/{owner}/{repo}/issues/{pr_number}/comments"
    request_json("POST", url, token, {"body": body})


def _patch_comment(
    api_url: str, token: str, owner: str, repo: str, comment_id: int, body: str
) -> None:
    url = f"{api_url}/repos/{owner}/{repo}/issues/comments/{comment_id}"
    request_json("PATCH", url, token, {"body": body})
